name: Last_life_III
version: '${project.version}'
main: net.olimpium.last_life_iii.Last_life_III
api-version: 1.16
authors: [ TheDracon, Cargandoc, Mario_Gandia ]
depend: [UltimateAdvancementAPI, ProtocolLib]
commands:
  LL3:
    description: Main last life command.
  link:
    description: Usado para linkear tu cuenta de discord
    usage: /<command> <token>
  crash:
    description: LOL
    usage: /<command> <player> <type>
  teamchat:
    description: Altera entre el chat de equipo y el global
    usage: /<command>
    aliases: [tc]
  teammenu:
    description: Abre el menu de tu team
    usage: /<command>
    aliases: [tm]
